1-Write a python code to reverse a string.

In [1]:
string="Million of problems,one Solution"
rev_string=(string)[::-1]
print(rev_string);

noituloS eno,smelborp fo noilliM

2-Write a python code to determine id a string is a palindrome.

In [2]:
string="abhinendra"
rev_string=string[::-1]
if string==rev_string:
  print("String is palindrome")
else:
    print("String is not pallindrome")

String is not pallindrome

3-Write a python code to determine if a number is an palindrome.

In [3]:
number=input ("Write a number");
rev_number=number[::-1]
if number==rev_number:
  print("Number is palindrome")
else:
  print("Number is not palindrome")

Number is not palindrome

4-Write a python code to reverse a list without using built-in functions.

In [4]:
football_team=["Raman","Radhe","Shyam","Manohar","Kishan","dhruv"]
print(football_team[::-1])

['dhruv', 'Kishan', 'Manohar', 'Shyam', 'Radhe', 'Raman']

5-Write a python code to find the minimum & maximum element in a array.

In [7]:
list=[]
n=int(input("range of elements"))
for i in range(0,n):
  ele=int(input())
  arr=list.append(ele)
print(list)
print(max(list))

KeyboardInterrupt: Interrupted by user

1- Write a python code to implement Numpy Task given below.

1)-Take 10 numbers from users and save into the array.

In [ ]:
import numpy as np

# Initialize an empty list to store the elements
elements = []
for i in range("10"):
    ele = int(input(f"Enter element {i+1}: "))
    elements.append(ele)

# Convert the list to a NumPy array
array = np.array(elements)

print("The NumPy array is:", array)

TypeError: 'int' object is not callable

2)-Print 2 to 8 numbers in numpy.

3)-Reshape the array in 5th dimensional array.

2- Write a python code to implement Numpy Task given below.

1)-Write a python code to implement Numpy Task given below.

2)-Sort the numbers without using the sort () function.

3)- Split the array into 4 Sections.

4)- Join the 4 sections into 2 sections and print the array.

Pandas

1- Create a dataFrame to add columns like Name,Roll,Department & College Name.

In [25]:
import pandas as pd

# Create an empty DataFrame with specified column names
team = pd.DataFrame(columns=['Name', 'Department', 'College'])
print(team)

Empty DataFrame
Columns: [Name, Department, College]
Index: []

2-Fill the columns with a minimum 10 columns.

In [26]:
import pandas as pd

l1=["John","Alpha","Doe"]
l2=["Computer Science and Engineering","Mechanical Engineering","Bio-technology"]
l3=["GLA University","IIT Kharagpur","IIT Bombay"]
# creating the DataFrame
team = pd.DataFrame((zip(l1, l2, l3)))
# adding column names to the respective columns
team.columns = ['Name', 'Department', 'College']

print(team)

    Name                        Department         College
0   John  Computer Science and Engineering  GLA University
1  Alpha            Mechanical Engineering   IIT Kharagpur
2    Doe                    Bio-technology      IIT Bombay

In [39]:
import pandas as pd
dataset={'Name':['Ram','Shyam','Dhruv','Prahalad','Gopi','kisan','Harshit','Mayank','Agochar','Dinkar Bhadauriya'],'Department':['CS','ME','IT','DA','DS','Biotech','Chemical Engineering',"ECE","Electrical Engineering",'Food and technology'],'College':['IIT Bombay','IIT Madras','IIT Delhi','IIT Guwahati','IIT Mandi','IIT Kanpur','IIT Jamshedpur','IIT Kharagpur','IIT BHU','IIT Roorkee']}
team=pd.DataFrame(dataset)
team

                Name              Department         College
0                Ram                      CS      IIT Bombay
1              Shyam                      ME      IIT Madras
2              Dhruv                      IT       IIT Delhi
3           Prahalad                      DA    IIT Guwahati
4               Gopi                      DS       IIT Mandi
5              kisan                 Biotech      IIT Kanpur
6            Harshit    Chemical Engineering  IIT Jamshedpur
7             Mayank                     ECE   IIT Kharagpur
8            Agochar  Electrical Engineering         IIT BHU
9  Dinkar Bhadauriya     Food and technology     IIT Roorkee

3-Analyze the dataFrame with the Funcions Head() & Tail.

In [40]:
team

                Name              Department         College
0                Ram                      CS      IIT Bombay
1              Shyam                      ME      IIT Madras
2              Dhruv                      IT       IIT Delhi
3           Prahalad                      DA    IIT Guwahati
4               Gopi                      DS       IIT Mandi
5              kisan                 Biotech      IIT Kanpur
6            Harshit    Chemical Engineering  IIT Jamshedpur
7             Mayank                     ECE   IIT Kharagpur
8            Agochar  Electrical Engineering         IIT BHU
9  Dinkar Bhadauriya     Food and technology     IIT Roorkee

In [41]:
team.head()

       Name Department       College
0       Ram         CS    IIT Bombay
1     Shyam         ME    IIT Madras
2     Dhruv         IT     IIT Delhi
3  Prahalad         DA  IIT Guwahati
4      Gopi         DS     IIT Mandi

In [42]:
team.tail()

                Name              Department         College
5              kisan                 Biotech      IIT Kanpur
6            Harshit    Chemical Engineering  IIT Jamshedpur
7             Mayank                     ECE   IIT Kharagpur
8            Agochar  Electrical Engineering         IIT BHU
9  Dinkar Bhadauriya     Food and technology     IIT Roorkee

4-Use info() & describe() function.

In [43]:
team.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        10 non-null     object
 1   Department  10 non-null     object
 2   College     10 non-null     object
dtypes: object(3)
memory usage: 372.0+ bytes

In [44]:
team.describe()

       Name Department     College
count    10         10          10
unique   10         10          10
top     Ram         CS  IIT Bombay
freq      1          1           1

5- Find out co-relations between the columns.

6- Convert the DataFrame into * CSV & *.excel file.